'use strict';

var examples = {
    'a': '啊',
    'ai': '爱',
    'an': '安',
    'ang': '昂',
    'ao': '奥',
    'e': '鹅',
    'ei': '诶',
    'en': '嗯',
    'eng': '鞥',
    'er': '尔',
    'o': '哦',
    'ou': '欧',

    'ba': '吧',
    'bai': '白',
    'ban': '班',
    'bang': '帮',
    'bao': '包',
    'bei': '被',
    'ben': '本',
    'beng': '崩',
    'bi': '必',
    'bian': '变',
    'biao': '表',
    'bie': '别',
    'bin': '宾',
    'bing': '冰',
    'bo': '播',
    'bu': '不',

    'ca': '擦',
    'cai': '彩',
    'can': '餐',
    'cang': '苍',
    'cao': '草',
    'ce': '测',
    'cen': '岑',
    'ceng': '层',
    'ci': '词',
    'cong': '从',
    'cou': '凑',
    'cu': '粗',
    'cuan': '窜',
    'cui': '催',
    'cun': '村',
    'cuo': '错',

    'da': '大',
    'dai': '代',
    'dan': '但',
    'dang': '当',
    'dao': '到',
    'de': '德',
    'dei': '得',
    'den': '扽',
    'deng': '等',
    'di': '帝',
    'dia': '嗲',
    'dian': '点',
    'diao': '钓',
    'die': '叠',
    'ding': '顶',
    'diu': '丢',
    'dong': '东',
    'dou': '斗',
    'du': '读',
    'duan': '短',
    'dui': '对',
    'dun': '顿',
    'duo': '多',

    'fa': '法',
    'fan': '翻',
    'fang': '方',
    'fei': '飞',
    'fen': '分',
    'feng': '风',
    'fo': '佛',
    'fou': '否',
    'fu': '服',

    'ga': '旮',
    'gai': '该',
    'gan': '干',
    'gang': '刚',
    'gao': '高',
    'ge': '个',
    'gei': '给',
    'gen': '跟',
    'geng': '更',
    'gong': '公',
    'gou': '狗',
    'gu': '谷',
    'gua': '瓜',
    'guai': '怪',
    'guan': '关',
    'guang': '光',
    'gui': '鬼',
    'gun': '滚',
    'guo': '国',

    'ha': '哈',
    'hai': '海',
    'han': '汉',
    'hang': '杭',
    'hao': '好',
    'he': '和',
    'hei': '黑',
    'hen': '很',
    'heng': '横',
    'hong': '红',
    'hou': '猴',
    'hu': '胡',
    'hua': '华',
    'huai': '坏',
    'huan': '欢',
    'huang': '黄',
    'hui': '灰',
    'hun': '昏',
    'huo': '火',

    'ji': '机',
    'jia': '家',
    'jian': '间',
    'jiang': '江',
    'jiao': '交',
    'jie': '杰',
    'jin': '金',
    'jing': '京',
    'jiong': '窘',
    'jiu': '旧',
    'ju': '居',
    'juan': '卷',
    'jue': '觉',
    'jun': '军',

    'ka': '卡',
    'kai': '开',
    'kan': '看',
    'kang': '康',
    'kao': '靠',
    'ke': '科',
    'kei': '尅',
    'ken': '肯',
    'keng': '坑',
    'kong': '空',
    'kou': '口',
    'ku': '哭',
    'kua': '夸',
    'kuai': '快',
    'kuan': '宽',
    'kuang': '框',
    'kui': '亏',
    'kun': '困',
    'kuo': '阔',

    'la': '拉',
    'lai': '来',
    'lan': '蓝',
    'lang': '狼',
    'lao': '老',
    'le': '乐',
    'lei': '累',
    'leng': '冷',
    'li': '里',
    'lia': '俩',
    'lian': '连',
    'liang': '凉',
    'liao': '聊',
    'lie': '列',
    'lin': '林',
    'ling': '领',
    'liu': '刘',
    'lo': '咯',
    'long': '龙',
    'lou': '楼',
    'lu': '路',
    'luan': '卵',
    'lun': '轮',
    'luo': '罗',
    'lv': '绿',
    'lve': '略',

    'ma': '马',
    'mai': '买',
    'man': '满',
    'mang': '忙',
    'mao': '猫',
    'me': '么',
    'mei': '没',
    'men': '门',
    'meng': '梦',
    'mi': '米',
    'mian': '面',
    'miao': '秒',
    'mie': '灭',
    'min': '民',
    'ming': '明',
    'miu': '谬',
    'mo': '魔',
    'mou': '某',
    'mu': '木',

    'na': '拿',
    'nai': '乃',
    'nan': '南',
    'nang': '囊',
    'nao': '脑',
    'ne': '呢',
    'nei': '内',
    'nen': '嫩',
    'neng': '能',
    'ni': '你',
    'nian': '年',
    'niang': '娘',
    'niao': '鸟',
    'nie': '捏',
    'nin': '您',
    'ning': '宁',
    'niu': '牛',
    'nong': '农',
    'nou': '耨',
    'nu': '努',
    'nuan': '暖',
    'nuo': '挪',
    'nv': '女',
    'nve': '虐',

    'pa': '爬',
    'pai': '牌',
    'pan': '潘',
    'pang': '胖',
    'pao': '炮',
    'pei': '配',
    'pen': '喷',
    'peng': '鹏',
    'pi': '皮',
    'pian': '片',
    'piao': '飘',
    'pie': '撇',
    'pin': '拼',
    'ping': '凭',
    'po': '破',
    'pou': '剖',
    'pu': '普',

    'qi': '齐',
    'qia': '洽',
    'qian': '前',
    'qiang': '墙',
    'qiao': '桥',
    'qie': '且',
    'qin': '琴',
    'qing': '轻',
    'qiong': '穷',
    'qiu': '秋',
    'qu': '去',
    'quan': '全',
    'que': '确',
    'qun': '群',

    'ran': '然',
    'rang': '让',
    'rao': '绕',
    're': '热',
    'ren': '仁',
    'reng': '仍',
    'ri': '日',
    'rong': '容',
    'rou': '肉',
    'ru': '如',
    'rua': '挼',
    'ruan': '软',
    'rui': '睿',
    'run': '润',
    'ruo': '若',

    'sa': '萨',
    'sai': '赛',
    'san': '伞',
    'sang': '桑',
    'sao': '扫',
    'se': '色',
    'sen': '森',
    'seng': '僧',
    'si': '司',
    'song': '松',
    'sou': '搜',
    'su': '苏',
    'suan': '酸',
    'sui': '岁',
    'sun': '孙',
    'suo': '锁',

    'ta': '它',
    'tai': '台',
    'tan': '谈',
    'tang': '汤',
    'tao': '涛',
    'te': '特',
    'tei': '忒',
    'teng': '疼',
    'ti': '体',
    'tian': '天',
    'tiao': '条',
    'tie': '贴',
    'ting': '听',
    'tong': '通',
    'tou': '头',
    'tu': '图',
    'tuan': '团',
    'tui': '推',
    'tun': '吞',
    'tuo': '拖',

    'wa': '哇',
    'wai': '外',
    'wan': '万',
    'wang': '王',
    'wei': '为',
    'wen': '文',
    'weng': '翁',
    'wo': '我',
    'wu': '无',

    'xi': '喜',
    'xia': '夏',
    'xian': '现',
    'xiang': '向',
    'xiao': '小',
    'xie': '谢',
    'xin': '心',
    'xing': '星',
    'xiong': '兄',
    'xiu': '秀',
    'xu': '徐',
    'xuan': '选',
    'xue': '学',
    'xun': '寻',

    'ya': '压',
    'yan': '燕',
    'yang': '羊',
    'yao': '药',
    'ye': '叶',
    'yi': '以',
    'yin': '音',
    'ying': '赢',
    'yo': '哟',
    'yong': '用',
    'you': '有',
    'yu': '与',
    'yuan': '元',
    'yue': '月',
    'yun': '云',

    'za': '咋',
    'zai': '在',
    'zan': '赞',
    'zang': '脏',
    'zao': '造',
    'ze': '则',
    'zei': '贼',
    'zen': '怎',
    'zeng': '增',
    'zi': '子',
    'zong': '宗',
    'zou': '走',
    'zu': '组',
    'zuan': '钻',
    'zui': '最',
    'zun': '遵',
    'zuo': '做',

    'cha': '茶',
    'chai': '拆',
    'chan': '产',
    'chang': '场',
    'chao': '超',
    'che': '车',
    'chen': '陈',
    'cheng': '成',
    'chi': '吃',
    'chong': '充',
    'chou': '丑',
    'chu': '出',
    'chua': '欻',
    'chuai': '踹',
    'chuan': '穿',
    'chuang': '床',
    'chui': '吹',
    'chun': '纯',
    'chuo': '戳',

    'sha': '沙',
    'shai': '晒',
    'shan': '山',
    'shang': '上',
    'shao': '少',
    'she': '设',
    'shen': '深',
    'sheng': '生',
    'shi': '是',
    'shou': '收',
    'shu': '书',
    'shua': '刷',
    'shuai': '帅',
    'shuan': '栓',
    'shuang': '双',
    'shui': '水',
    'shun': '顺',
    'shuo': '说',

    'zha': '炸',
    'zhai': '摘',
    'zhan': '占',
    'zhang': '张',
    'zhao': '赵',
    'zhe': '者',
    'zhei': '这',
    'zhen': '真',
    'zheng': '正',
    'zhi': '之',
    'zhong': '中',
    'zhou': '周',
    'zhu': '主',
    'zhua': '爪',
    'zhuai': '拽',
    'zhuan': '专',
    'zhuang': '装',
    'zhui': '追',
    'zhun': '准',
    'zhuo': '捉'
};
var allowPairs = {
    '': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'er',
        'o',
        'ou'
    ],
    'b': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'ei',
        'en',
        'eng',
        'i',
        'ian',
        'iao',
        'ie',
        'in',
        'ing',
        'o',
        'u'
    ],
    'c': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    'd': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'i',
        'ia',
        'ian',
        'iao',
        'ie',
        'ing',
        'iu',
        'ong',
        'ou',
        'u',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    'f': [
        'a',
        'an',
        'ang',
        'ei',
        'en',
        'eng',
        'o',
        'ou',
        'u'
    ],
    'g': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'ong',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ],
    'h': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'ong',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ],
    'j': [
        'i',
        'ia',
        'ian',
        'iang',
        'iao',
        'ie',
        'in',
        'ing',
        'iong',
        'iu',
        'u',
        'uan',
        'ue',
        'un'
    ],
    'k': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'ong',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ],
    'l': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'eng',
        'i',
        'ia',
        'ian',
        'iang',
        'iao',
        'ie',
        'in',
        'ing',
        'iu',
        'o',
        'ong',
        'ou',
        'u',
        'uan',
        'un',
        'uo',
        'v',
        've'
    ],
    'm': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'i',
        'ian',
        'iao',
        'ie',
        'in',
        'ing',
        'iu',
        'o',
        'ou',
        'u'
    ],
    'n': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'i',
        'ian',
        'iang',
        'iao',
        'ie',
        'in',
        'ing',
        'iu',
        'ong',
        'ou',
        'u',
        'uan',
        'uo',
        'v',
        've'
    ],
    'p': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'ei',
        'en',
        'eng',
        'i',
        'ian',
        'iao',
        'ie',
        'in',
        'ing',
        'o',
        'ou',
        'u'
    ],
    'q': [
        'i',
        'ia',
        'ian',
        'iang',
        'iao',
        'ie',
        'in',
        'ing',
        'iong',
        'iu',
        'u',
        'uan',
        'ue',
        'un'
    ],
    'r': [
        'an',
        'ang',
        'ao',
        'e',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'ua',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    's': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    't': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'eng',
        'i',
        'ian',
        'iao',
        'ie',
        'ing',
        'ong',
        'ou',
        'u',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    'w': [
        'a',
        'ai',
        'an',
        'ang',
        'ei',
        'en',
        'eng',
        'o',
        'u'
    ],
    'x': [
        'i',
        'ia',
        'ian',
        'iang',
        'iao',
        'ie',
        'in',
        'ing',
        'iong',
        'iu',
        'u',
        'uan',
        'ue',
        'un'
    ],
    'y': [
        'a',
        'an',
        'ang',
        'ao',
        'e',
        'i',
        'in',
        'ing',
        'o',
        'ong',
        'ou',
        'u',
        'uan',
        'ue',
        'un'
    ],
    'z': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'uan',
        'ui',
        'un',
        'uo'
    ],
    'ch': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ],
    'sh': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'en',
        'eng',
        'i',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ],
    'zh': [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'e',
        'ei',
        'en',
        'eng',
        'i',
        'ong',
        'ou',
        'u',
        'ua',
        'uai',
        'uan',
        'uang',
        'ui',
        'un',
        'uo'
    ]
};
var allowUgmus = [];
for (var ugmu in allowPairs) {
    allowUgmus.push(ugmu)
}