/** last changed: 2018.11.10 */

Shuang.resource.scheme.xiaolang = {
  id: 'xiaolang',
  name: '小浪双拼',
  tips: [
    '常用输入法几乎不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'v',
      zh: 'e'
    },
    yun: {
      a: 'a',
      ai: 'k',
      an: 'j',
      ang: 'h',
      ao: 's',
      e: 'e',
      ei: 'w',
      en: 'm',
      eng: 'n',
      i: 'i',
      ia: 'k',
      ian: 'f',
      iang: 'm',
      iao: 'c',
      ie: 'p',
      iong: 'j',
      in: 'd',
      ing: 'v',
      iu: 't',
      o: 'o',
      ong: 'l',
      ou: 'r',
      u: 'u',
      ua: 'f',
      uai: 'v',
      uan: 'g',
      uang: 'z',
      ue: 'b',
      ui: 'd',
      un: 'y',
      uo: 'o',
      v: 'x',
      ve: 'b'
    },
    other: {
      a: 'aa',
      ai: 'ai',
      an: 'an',
      ang: 'ah',
      ao: 'ao',
      e: 'uu',
      ei: 'ui',
      en: 'un',
      eng: 'un',
      er: 'ur',
      o: 'oo',
      ou: 'ou'
    }
  }
}