"use strict";

/** last changed: 2018.3.24 */

var scheme = {
  id: 'jmdkudpn6',
  name: '键道双拼6',
  tips: [
    'jqxy 遇 u 以 v 替代'
    , '飞键限制：若不了解，不推荐学习'
    , '<i>极小众方案 - 常用输入法不内置</i>'
  ],
  detail: {
    ugmu: {
      b: 'b'
      , c: 'c'
      , d: 'd'
      , f: 'f'
      , g: 'g'
      , h: 'h'
      , j: 'j'
      , k: 'k'
      , l: 'l'
      , m: 'm'
      , n: 'n'
      , p: 'p'
      , q: 'q'
      , r: 'r'
      , s: 's'
      , t: 't'
      , w: 'w'
      , x: 'x'
      , y: 'y'
      , z: 'z'
      , ch: ['j', 'w']
      , sh: 'e'
      , zh: ['f', 'q']
    }
    , ypmu: {
      a: 's'
      , ai: 'h'
      , an: 'f'
      , ang: 'p'
      , ao: 'z'
      , e: 'e'
      , ei: 'w'
      , en: 'n'
      , eng: 'r'
      , i: 'k'
      , ia: 's'
      , ian: 'm'
      , iang: 'x'
      , iao: 'c'
      , ie: 'd'
      , iong: 'y'
      , in: 'b'
      , ing: 'g'
      , iu: 'q'
      , o: 'l'
      , ong: 'y'
      , ou: 'd'
      , u: 'j'
      , ua: 'q'
      , uai: 'g'
      , uan: 't'
      , uang: 'x'
      , ue: 'h'
      , ui: 'b'
      , un: 'w'
      , uo: 'l'
      , v: 'l'
      , ve: 'h'
    }
    , teuu: {
      a: 'xs'
      , ai: 'xh'
      , an: 'xf'
      , ang: 'xp'
      , ao: 'xz'
      , e: 'xe'
      , ei: 'xw'
      , en: 'xn'
      , eng: 'xr'
      , er: 'xj'
      , o: 'xl'
      , ou: 'xd'
    }
    , fzjm: {
      cha: 'ws'
      , chai: 'jh'
      , chan: 'jf'
      , chang: 'jp'
      , chen: 'jn'
      , cheng: 'jr'
      , chi: 'wk'
      , chong: 'wy'
      , chou: 'wd'
      , chu: 'jj'
      , chua: 'wq'
      , chuai: 'wg'
      , chuan: 'wt'
      , chuang: 'wx'
      , chui: 'wb'
      , chun: 'jw'
      , chuo: 'wl'
      , ju: 'jl'
      , qu: 'ql'
      , xu: 'xl'
      , yu: 'yl'
      , zha: 'fs'
      , zhan: 'qf'
      , zhang: 'qp'
      , zhen: 'qn'
      , zheng: 'qr'
      , zhi: 'fk'
      , zhong: 'fy'
      , zhou: 'fd'
      , zhu: 'qj'
      , zhua: 'fq'
      , zhuai: 'fg'
      , zhuan: 'ft'
      , zhuang: 'fx'
      , zhui: 'fb'
      , zhun: 'qw'
      , zhuo: 'fl'
    }
  }
};