module.exports = {
  name: 'daniu',
  name1: '大牛',
  name2: '双拼',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'ua', yun2: 'ian' },
    { alphabet: 'W', yun1: 'vn', yun2: 'ei' },
    { alphabet: 'E', yun1: 'e' },
    { alphabet: 'R', yun1: 'ou' },
    { alphabet: 'T', yun1: 'iu' },
    { alphabet: 'Y', yun1: 'un' },
    { alphabet: 'U', sheng: 'sh', yun1: 'u', yun2: 'er' },
    { alphabet: 'I', sheng: 'ch', yun1: 'i' },
    { alphabet: 'O', sheng: 'zh', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ie' },
  ],
  row2: [
    { alphabet: 'A', sheng: 'zh', yun1: 'a' },
    { alphabet: 'S', yun1: 'ao' },
    { alphabet: 'D', yun1: 'an' },
    { alphabet: 'F', yun1: 'ang' },
    { alphabet: 'G', yun1: 'uai', yun2: 'ing' },
    { alphabet: 'H', yun1: 'ai', yun2: 'ue' },
    { alphabet: 'J', yun1: 'eng', yun2: 'van' },
    { alphabet: 'K', yun1: 'en', yun2: 'ia' },
    { alphabet: 'L', yun1: 'ong', yun2: 'iong' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'uan' },
    { alphabet: 'X', yun1: 've', yun2: 'uang' },
    { alphabet: 'C', yun1: 'ian' },
    { alphabet: 'V', sheng: 'sh', yun1: 'ui', yun2: 'v' },
    { alphabet: 'B', yun1: 'in' },
    { alphabet: 'N', yun1: 'ui', yun2: 'iang' },
    { alphabet: 'M', yun1: 'iao' },
  ],
  table1: [
    { yun: 'a', bianma: 'ea' },
    { yun: 'ai', bianma: 'eh' },
    { yun: 'an', bianma: 'ed' },
    { yun: 'ang', bianma: 'ef' },
    { yun: 'ao', bianma: 'es' },
  ],
  table2: [
    { yun: 'e', bianma: 'ee' },
    { yun: 'ei', bianma: 'ew' },
    { yun: 'en', bianma: 'ek' },
    { yun: 'eng', bianma: 'ej' },
    { yun: 'er', bianma: 'eu' },
  ],
  table3: [
    { yun: 'o', bianma: 'eo' },
    { yun: 'ou', bianma: 'er' },
  ],
  hant: {
    name2: '雙拼',
    tableName: '零聲母',
  }
}