module.exports = {
  name: 'guobiao',
  name1: '国标',
  name2: '双拼',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'ia', yun2: 'ua' },
    { alphabet: 'W', yun1: 'van', yun2: 'uan' },
    { alphabet: 'E', yun1: 'e' },
    { alphabet: 'R', yun1: 'en' },
    { alphabet: 'T', yun1: 'ie' },
    { alphabet: 'Y', yun1: 'iu', yun2: 'uai' },
    { alphabet: 'U', sheng: 'sh', yun1: 'u' },
    { alphabet: 'I', sheng: 'ch', yun1: 'i' },
    { alphabet: 'O', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ou' },
  ],
  row2: [
    { alphabet: 'A', yun1: 'a' },
    { alphabet: 'S', yun1: 'iong', yun2: 'ong' },
    { alphabet: 'D', yun1: 'ian' },
    { alphabet: 'F', yun1: 'an' },
    { alphabet: 'G', yun1: 'ang' },
    { alphabet: 'H', yun1: 'eng' },
    { alphabet: 'J', yun1: 'ing' },
    { alphabet: 'K', yun1: 'ai' },
    { alphabet: 'L', yun1: 'in', yun2: 'er' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'vn', yun2: 'un' },
    { alphabet: 'X', yun1: 've' },
    { alphabet: 'C', yun1: 'ao' },
    { alphabet: 'V', sheng: 'zh', yun1: 'v', yun2: 'ui' },
    { alphabet: 'B', yun1: 'ei' },
    { alphabet: 'N', yun1: 'iang', yun2: 'uang' },
    { alphabet: 'M', yun1: 'iao' },
  ],
  table1: [
    { yun: 'a', bianma: 'aa' },
    { yun: 'ai', bianma: 'ak' },
    { yun: 'an', bianma: 'af' },
    { yun: 'ang', bianma: 'ag' },
    { yun: 'ao', bianma: 'ac' },
  ],
  table2: [
    { yun: 'e', bianma: 'ae' },
    { yun: 'ei', bianma: 'ab' },
    { yun: 'en', bianma: 'ar' },
    { yun: 'eng', bianma: 'ah' },
    { yun: 'er', bianma: 'al' },
  ],
  table3: [
    { yun: 'o', bianma: 'ao' },
    { yun: 'ou', bianma: 'ap' },
  ],
  hant: {
    name1: '國標',
    name2: '雙拼',
    tableName: '零聲母',
  }
}