module.exports = {
  name: 'jiandao6',
  name1: '键道',
  name2: '双拼',
  name3: '6',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', sheng: 'zh', yun1: 'ua', yun2: 'iu' },
    { alphabet: 'W', sheng: 'ch', yun1: 'ei', yun2: 'un' },
    { alphabet: 'E', sheng: 'sh', yun1: 'e' },
    { alphabet: 'R', yun1: 'eng' },
    { alphabet: 'T', yun1: 'uan' },
    { alphabet: 'Y', yun1: 'ong', yun2: 'iong' },
    { alphabet: 'U' },
    { alphabet: 'I' },
    { alphabet: 'O' },
    { alphabet: 'P', yun1: 'ang' },
  ],
  row2: [
    { alphabet: 'A' },
    { alphabet: 'S', yun1: 'a', yun2: 'ia' },
    { alphabet: 'D', yun1: 'ou', yun2: 'ie' },
    { alphabet: 'F', sheng: 'zh', yun1: 'an' },
    { alphabet: 'G', yun1: 'uai', yun2: 'ing' },
    { alphabet: 'H', yun1: 'ai', yun2: 'ue' },
    { alphabet: 'J', sheng: 'ch', yun1: 'u', yun2: 'er' },
    { alphabet: 'K', yun1: 'i' },
    { alphabet: 'L', yun1: 'uo', yun2: 'v,o' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'ao' },
    { alphabet: 'X', yun1: 'iang', yun2: 'uang' },
    { alphabet: 'C', yun1: 'iao' },
    { alphabet: 'V' },
    { alphabet: 'B', yun1: 'in', yun2: 'ui' },
    { alphabet: 'N', yun1: 'en' },
    { alphabet: 'M', yun1: 'ian', yun2: 'uang' },
  ],
  table1: [
    { yun: 'a', bianma: 'xs' },
    { yun: 'ai', bianma: 'xh' },
    { yun: 'an', bianma: 'xf' },
    { yun: 'ang', bianma: 'xp' },
    { yun: 'ao', bianma: 'xz' },
  ],
  table2: [
    { yun: 'e', bianma: 'xe' },
    { yun: 'ei', bianma: 'xw' },
    { yun: 'en', bianma: 'xn' },
    { yun: 'eng', bianma: 'xr' },
    { yun: 'er', bianma: 'xj' },
  ],
  table3: [
    { yun: 'o', bianma: 'xl' },
    { yun: 'ou', bianma: 'xd' },
  ],
  hant: {
    name1: '鍵道',
    name2: '雙拼',
    tableName: '零聲母',
  }
}