module.exports = {
  name: 'xiaoguan',
  name1: '开源',
  name2: '小鹳',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'iu' },
    { alphabet: 'W', yun1: 'ei' },
    { alphabet: 'E', yun1: 'e' },
    { alphabet: 'R', yun1: 'uan', yun2: 'er' },
    { alphabet: 'T', yun1: 've', yun2: 'ue' },
    { alphabet: 'Y', yun1: 'un' },
    { alphabet: 'U', sheng: 'sh', yun1: 'u' },
    { alphabet: 'I', sheng: 'ch', yun1: 'i' },
    { alphabet: 'O', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ie' },
  ],
  row2: [
    { alphabet: 'A', yun1: 'a' },
    { alphabet: 'S', yun1: 'ong', yun2: 'iong' },
    { alphabet: 'D', yun1: 'ing', yun2: 'uai' },
    { alphabet: 'F', yun1: 'en' },
    { alphabet: 'G', yun1: 'eng' },
    { alphabet: 'H', yun1: 'ang' },
    { alphabet: 'J', yun1: 'an' },
    { alphabet: 'K', yun1: 'ai', yun2: 'ue' },
    { alphabet: 'L', yun1: 'iang', yun2: 'uang' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'ou' },
    { alphabet: 'X', yun1: 'ia', yun2: 'ua' },
    { alphabet: 'C', yun1: 'ao' },
    { alphabet: 'V', sheng: 'zh', yun1: 'v', yun2: 'ui' },
    { alphabet: 'B', yun1: 'in' },
    { alphabet: 'N', yun1: 'iao' },
    { alphabet: 'M', yun1: 'ian' },
  ],
  table1: [
    { yun: 'a', bianma: 'aa   /   oa' },
    { yun: 'ai', bianma: 'ai   /   ok' },
    { yun: 'an', bianma: 'an   /   oj' },
    { yun: 'ang', bianma: 'ah   /   oh' },
    { yun: 'ao', bianma: 'ao   /   oc' },
  ],
  table2: [
    { yun: 'e', bianma: 'ee   /   oe' },
    { yun: 'ei', bianma: 'ei   /   ow' },
    { yun: 'en', bianma: 'en   /   of' },
    { yun: 'eng', bianma: 'eg   /   og' },
    { yun: 'er', bianma: 'er   /   or' },
  ],
  table3: [
    { yun: 'o', bianma: 'oo' },
    { yun: 'ou', bianma: 'ou   /   oz' },
  ],
  const: {
    tableStartX: 210,
    tableCellWidth: 267,
    tableCellYunEndX: 186,
    tableNameStartX: 918,
  },
  hant: {
    name1: '開源',
    name2: '小鸛',
    tableName: '零聲母',
  }
}