module.exports = {
  name: 'xiaolang',
  name1: '小浪',
  name2: '双拼',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q' },
    { alphabet: 'W', yun1: 'ei' },
    { alphabet: 'E', sheng: 'zh', yun1: 'e' },
    { alphabet: 'R', yun1: 'ou' },
    { alphabet: 'T', yun1: 'iu' },
    { alphabet: 'Y', yun1: 'un', yun2: 'vn' },
    { alphabet: 'U', yun1: 'u' },
    { alphabet: 'I', sheng: 'ch', yun1: 'i' },
    { alphabet: 'O', yun1: 'uo', yun2: 'o' },
    { alphabet: 'P', yun1: 'ie' },
  ],
  row2: [
    { alphabet: 'A', yun1: 'a' },
    { alphabet: 'S', yun1: 'ao' },
    { alphabet: 'D', yun1: 'ui', yun2: 'in' },
    { alphabet: 'F', yun1: 'ian', yun2: 'ua' },
    { alphabet: 'G', yun1: 'uan' },
    { alphabet: 'H', yun1: 'ang' },
    { alphabet: 'J', yun1: 'an', yun2: 'iong' },
    { alphabet: 'K', yun1: 'ai', yun2: 'ia' },
    { alphabet: 'L', yun1: 'ong' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'uang' },
    { alphabet: 'X', yun1: 'v' },
    { alphabet: 'C', yun1: 'iao' },
    { alphabet: 'V', sheng: 'sh', yun1: 'ing', yun2: 'uai' },
    { alphabet: 'B', yun1: 'ue', yun2: 've' },
    { alphabet: 'N', yun1: 'eng' },
    { alphabet: 'M', yun1: 'en', yun2: 'iang' },
  ],
  table1: [
    { yun: 'a', bianma: 'aa' },
    { yun: 'ai', bianma: 'ai' },
    { yun: 'an', bianma: 'an' },
    { yun: 'ang', bianma: 'ah' },
    { yun: 'ao', bianma: 'ao' },
  ],
  table2: [
    { yun: 'e', bianma: 'uu' },
    { yun: 'ei', bianma: 'ui' },
    { yun: 'en', bianma: 'un' },
    { yun: 'eng', bianma: 'un' },
    { yun: 'er', bianma: 'ur' },
  ],
  table3: [
    { yun: 'o', bianma: 'oo' },
    { yun: 'ou', bianma: 'ou' },
  ],
  hant: {
    name2: '雙拼',
    tableName: '零聲母',
  }
}