module.exports = {
  name: 'xingkong',
  name1: '星空',
  name2: '双拼',
  name3: '一笔',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'iu' },
    { alphabet: 'W', yun1: 'ei' },
    { alphabet: 'E', bihua: '一', yun1: 'e' },
    { alphabet: 'R', yun1: 'ou' },
    { alphabet: 'T', yun1: 'uan' },
    { alphabet: 'Y', yun1: 'un' },
    { alphabet: 'U', bihua: '丿', yun1: 'u', yun2: 'er' },
    { alphabet: 'I', bihua: '丨', yun1: 'i' },
    { alphabet: 'O', bihua: '丶', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ang' },
  ],
  row2: [
    { alphabet: 'A', bihua: '乛', yun1: 'a' },
    { alphabet: 'S', sheng: 'sh', yun1: 'ia', yun2: 'ua' },
    { alphabet: 'D', yun1: 'iao' },
    { alphabet: 'F', yun1: 'ian' },
    { alphabet: 'G', yun1: 'uai', yun2: 'ing' },
    { alphabet: 'H', yun1: 'ai', yun2: 'ue' },
    { alphabet: 'J', yun1: 'an' },
    { alphabet: 'K', yun1: 'ao' },
    { alphabet: 'L', yun1: 'iong', yun2: 'ong' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', sheng: 'zh', yun1: 've' },
    { alphabet: 'X', yun1: 'ie' },
    { alphabet: 'C', sheng: 'ch', yun1: 'iang', yun2: 'uang' },
    { alphabet: 'V', yun1: 'v', yun2: 'ui' },
    { alphabet: 'B', yun1: 'in' },
    { alphabet: 'N', yun1: 'en' },
    { alphabet: 'M', yun1: 'eng' },
  ],
  table1: [
    { yun: 'a', bianma: 'va' },
    { yun: 'ai', bianma: 'vh' },
    { yun: 'an', bianma: 'vj' },
    { yun: 'ang', bianma: 'vp' },
    { yun: 'ao', bianma: 'vk' },
  ],
  table2: [
    { yun: 'e', bianma: 've' },
    { yun: 'ei', bianma: 'vw' },
    { yun: 'en', bianma: 'vn' },
    { yun: 'eng', bianma: 'vm' },
    { yun: 'er', bianma: 'vu' },
  ],
  table3: [
    { yun: 'o', bianma: 'vo' },
    { yun: 'ou', bianma: 'vr' },
  ],
  const: {
    name3Color: '#c12d30',
    name3Stroke: '#c12d30',
    name3FontSize: 36,
  },
  hant: {
    name2: '雙拼',
    name3: '一筆',
    tableName: '零聲母',
  }
}