module.exports = {
  name: 'yunbiaokuaipin',
  name1: '韵标',
  name2: '块拼',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'ian' },
    { alphabet: 'W', yun1: 'ua', yun2: 've' },
    { alphabet: 'E', yun1: 'e' },
    { alphabet: 'R', yun1: 'iang' },
    { alphabet: 'T', yun1: 'eng' },
    { alphabet: 'Y', yun1: 'ie', yun2: 'uai' },
    { alphabet: 'U', sheng: 'ch', yun1: 'u' },
    { alphabet: 'I', sheng: 'sh', yun1: 'i' },
    { alphabet: 'O', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ai' },
  ],
  row2: [
    { alphabet: 'A', sheng: 'zh', yun1: 'a' },
    { alphabet: 'S', yun1: 'un' },
    { alphabet: 'D', yun1: 'uan' },
    { alphabet: 'F', yun1: 'iao' },
    { alphabet: 'G', yun1: 'uang', yun2: 'ing' },
    { alphabet: 'H', yun1: 'ong', yun2: 'iong' },
    { alphabet: 'J', yun1: 'ia' },
    { alphabet: 'K', yun1: 'ei' },
    { alphabet: 'L', yun1: 'ou' },
    { alphabet: ';' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'an' },
    { alphabet: 'X', yun1: 'iu' },
    { alphabet: 'C', yun1: 'ao' },
    { alphabet: 'V', yun1: 'v', yun2: 'ui' },
    { alphabet: 'B', yun1: 'ei' },
    { alphabet: 'N', yun1: 'en' },
    { alphabet: 'M', yun1: 'ang' },
  ],
  table1: [
    { yun: 'a', bianma: 'ea' },
    { yun: 'ai', bianma: 'ep' },
    { yun: 'an', bianma: 'ez' },
    { yun: 'ang', bianma: 'em' },
    { yun: 'ao', bianma: 'ec' },
  ],
  table2: [
    { yun: 'e', bianma: 'ee' },
    { yun: 'ei', bianma: 'ek' },
    { yun: 'en', bianma: 'en' },
    { yun: 'eng', bianma: 'et' },
    { yun: 'er', bianma: 'er' },
  ],
  table3: [
    { yun: 'o', bianma: 'eo' },
    { yun: 'ou', bianma: 'el' },
  ],
  hant: {
    name1: '韻標',
    name2: '塊拼',
    tableName: '零聲母',
  }
}