module.exports = {
  name: 'ziguang',
  name1: '紫光',
  name2: '双拼',
  tableName: '零声母',
  row1: [
    { alphabet: 'Q', yun1: 'ao' },
    { alphabet: 'W', yun1: 'en' },
    { alphabet: 'E', yun1: 'e' },
    { alphabet: 'R', yun1: 'an' },
    { alphabet: 'T', yun1: 'eng' },
    { alphabet: 'Y', yun1: 'in', yun2: 'uai' },
    { alphabet: 'U', sheng: 'zh', yun1: 'u' },
    { alphabet: 'I', sheng: 'sh', yun1: 'i' },
    { alphabet: 'O', yun1: 'o', yun2: 'uo' },
    { alphabet: 'P', yun1: 'ai' },
  ],
  row2: [
    { alphabet: 'A', sheng: 'ch', yun1: 'a' },
    { alphabet: 'S', yun1: 'ang' },
    { alphabet: 'D', yun1: 'ie' },
    { alphabet: 'F', yun1: 'ian' },
    { alphabet: 'G', yun1: 'iang', yun2: 'uang' },
    { alphabet: 'H', yun1: 'iong', yun2: 'ong' },
    { alphabet: 'J', yun1: 'er', yun2: 'iu' },
    { alphabet: 'K', yun1: 'ei' },
    { alphabet: 'L', yun1: 'uan' },
    { alphabet: ';', yun1: 'ing' },
  ],
  row3: [
    { alphabet: 'Z', yun1: 'ou' },
    { alphabet: 'X', yun1: 'ia', yun2: 'ua' },
    { alphabet: 'C' },
    { alphabet: 'V', yun1: 'v' },
    { alphabet: 'B', yun1: 'iao' },
    { alphabet: 'N', yun1: 'ue', yun2: 'ui' },
    { alphabet: 'M', yun1: 'un' },
  ],
  table1: [
    { yun: 'a', bianma: 'oa' },
    { yun: 'ai', bianma: 'op' },
    { yun: 'an', bianma: 'or' },
    { yun: 'ang', bianma: 'os' },
    { yun: 'ao', bianma: 'oq' },
  ],
  table2: [
    { yun: 'e', bianma: 'oe' },
    { yun: 'ei', bianma: 'ok' },
    { yun: 'en', bianma: 'ow' },
    { yun: 'eng', bianma: 'ot' },
    { yun: 'er', bianma: 'oj' },
  ],
  table3: [
    { yun: 'o', bianma: 'oo' },
    { yun: 'ou', bianma: 'oz' },
  ],
  hant: {
    name2: '雙拼',
    tableName: '零聲母',
  }
}