/** last changed: 2022.11.09 */

Shuang.resource.scheme.baiyun = {
  id: 'baiyun',
  name: '白云双拼',
  tips: [
    '常用输入法不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'v',
      zh: 'u'
    },
    yun: {
      a: 'a',
      ai: 'j',
      an: 'd',
      ang: 'f',
      ao: 'c',
      e: 'e',
      ei: 'w',
      en: 'k',
      eng: 'z',
      i: 'i',
      ia: 'k',
      ian: 'm',
      iang: 'h',
      iao: 'n',
      ie: 'p',
      iong: 'l',
      in: 'b',
      ing: 'g',
      iu: 't',
      o: 'o',
      ong: 'l',
      ou: 's',
      u: 'u',
      ua: 'x',
      uai: 'v',
      uan: 'r',
      uang: 'g',
      ue: 'j',
      ui: 'h',
      un: 'y',
      uo: 'o',
      v: 'v',
      ve: 'x'
    },
    other: {
      a: 'aa',
      ai: 'ai',
      an: 'an',
      ang: 'af',
      ao: 'ao',
      e: 'ee',
      ei: 'ei',
      en: 'en',
      eng: 'ez',
      er: 'er',
      o: 'oo',
      ou: 'ou'
    }
  }
}