/** last changed: 2022.9.20 */

Shuang.resource.scheme.daniu = {
  id: 'daniu',
  name: '大牛双拼',
  tips: [
    '常用输入法几乎不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      zh: ['a', 'o'],
      ch: 'i',
      sh: ['u', 'v']
    },
    yun: {
      a: 'a',
      ai: 'h',
      an: 'd',
      ang: 'f',
      ao: 's',
      e: 'e',
      ei: 'w',
      en: 'k',
      eng: 'j',
      i: 'i',
      ia: 'k',
      ian: ['c', 'q'],
      iang: 'n',
      iao: 'm',
      ie: 'p',
      iong: 'l',
      in: 'b',
      ing: 'g',
      iu: 't',
      o: 'o',
      ong: 'l',
      ou: 'r',
      u: 'u',
      ua: 'q',
      uai: 'g',
      uan: 'z',
      uang: 'x',
      ue: ['h', 'x'],
      ui: ['n', 'v'],
      un: 'y',
      uo: 'o',
      v: 'v',
      ve: 'x'
    },
    other: {
      a: 'ea',
      ai: 'eh',
      an: 'ed',
      ang: 'ef',
      ao: 'es',
      e: 'ee',
      ei: 'ew',
      en: 'ek',
      eng: 'ej',
      er: 'eu',
      o: 'eo',
      ou: 'er',
      juan: ['jz', 'jj'],
      jun: ['jy', 'jw'],
      quan: ['qz', 'qj'],
      qun: ['qy', 'qw'],
      xuan: ['xz', 'xj'],
      xun: ['xy', 'xw'],
      yuan: ['yz', 'yj'],
      yun: ['yy', 'yw']
    }
  },
  show: {
    lingShengMu: {
      a: 'ea',
      ai: 'eh',
      an: 'ed',
      ang: 'ef',
      ao: 'es',
      e: 'ee',
      ei: 'ew',
      en: 'ek',
      eng: 'ej',
      er: 'eu',
      o: 'eo',
      ou: 'er'
    },
    other: {
      q: 'ian',
      w_push: 'vn',
      u: 'er',
      g_push: 'uai',
      j: 'van',
      l_push: 'ong',
      x_push: 've',
      c_2: '',
      v_push: 'ui',
      n_push: 'ui'
    }
  }
}