/** last changed: 2019.8.23 */

Shuang.resource.scheme.guobiao = {
  id: 'guobiao',
  name: '国标双拼',
  tips: [
    '推荐性国家标准 : GB/T 34947-2017',
    '常用输入法几乎不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'u',
      zh: 'v'
    },
    yun: {
      a: 'a',
      ai: 'k',
      an: 'f',
      ang: 'g',
      ao: 'c',
      e: 'e',
      ei: 'b',
      en: 'r',
      eng: 'h',
      i: 'i',
      ia: 'q',
      ian: 'd',
      iang: 'n',
      iao: 'm',
      ie: 't',
      iong: 's',
      in: 'l',
      ing: 'j',
      iu: 'y',
      o: 'o',
      ong: 's',
      ou: 'p',
      u: 'u',
      ua: 'q',
      uai: 'y',
      uan: 'w',
      uang: 'n',
      ue: 'x',
      ui: 'v',
      un: 'z',
      uo: 'o',
      v: 'v',
      ve: 'x'
    },
    other: {
      a: 'aa',
      ai: 'ak',
      an: 'af',
      ang: 'ag',
      ao: 'ac',
      e: 'ae',
      ei: 'ab',
      en: 'ar',
      eng: 'ah',
      er: 'al',
      o: 'ao',
      ou: 'ap'
    }
  }
}