/** last changed: 2019.11.26 */

Shuang.resource.scheme.xiaoyue = {
  id: 'xiaoyue',
  name: '小月双拼',
  tips: [
    '常用输入法不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'u',
      zh: 'v'
    },
    yun: {
      a: 'a',
      ai: 'k',
      an: 'j',
      ang: 'd',
      ao: 's',
      e: 'e',
      ei: 'w',
      en: 'f',
      eng: 'z',
      i: 'i',
      ia: 'k',
      ian: 'm',
      iang: 'f',
      iao: 'n',
      ie: 'p',
      iong: 'j',
      in: 'g',
      ing: 'v',
      iu: 't',
      o: 'o',
      ong: 'x',
      ou: 'r',
      u: 'u',
      ua: 'c',
      uai: 'b',
      uan: 'l',
      uang: 'v',
      ue: 'h',
      ui: 'g',
      un: 'y',
      uo: 'o',
      v: 'q',
      ve: 'h'
    },
    other: {
      a: 'aa',
      ai: 'ai',
      an: 'an',
      ang: 'ad',
      ao: 'ao',
      e: 'ee',
      ei: 'ei',
      en: 'en',
      eng: 'ez',
      er: 'er',
      o: 'oo',
      ou: 'ou'
    }
  }
}
