/** last changed: 2018.11.10 */

Shuang.resource.scheme.xiaohe = {
  id: 'xiaohe',
  name: '小鹤双拼',
  tips: [
    'iOS (>=12.1.1) 自带方案'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'u',
      zh: 'v'
    },
    yun: {
      a: 'a',
      ai: 'd',
      an: 'j',
      ang: 'h',
      ao: 'c',
      e: 'e',
      ei: 'w',
      en: 'f',
      eng: 'g',
      i: 'i',
      ia: 'x',
      ian: 'm',
      iang: 'l',
      iao: 'n',
      ie: 'p',
      iong: 's',
      in: 'b',
      ing: 'k',
      iu: 'q',
      o: 'o',
      ong: 's',
      ou: 'z',
      u: 'u',
      ua: 'x',
      uai: 'k',
      uan: 'r',
      uang: 'l',
      ue: 't',
      ui: 'v',
      un: 'y',
      uo: 'o',
      v: 'v',
      ve: 't'
    },
    other: {
      a: 'aa',
      ai: 'ai',
      an: 'an',
      ang: 'ah',
      ao: 'ao',
      e: 'ee',
      ei: 'ei',
      en: 'en',
      eng: 'eg',
      er: 'er',
      o: 'oo',
      ou: 'ou'
    }
  }
}