/** last changed: 2022.08.28 */

Shuang.resource.scheme.xiaoyue = {
  id: 'xiaoyue',
  name: '小月双拼',
  tips: [
    '舒适手感',
    '常用输入法不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'i',
      sh: 'u',
      zh: 'v'
    },
    yun: {
      iu: "q",
      ei: "w",
      e: "e",
      uan: "r",
      er: "r",
      un: "t",
      ue: "y",
      ve: "y",
      u: "u",
      i: "i",
      o: "o",
      uo: "o",
      ie: "p",
      a: "a",
      an: "s",
      ang: "d",
      en: "f",
      eng: "g",
      ong: "h",
      iong: "h",
      ian: "j",
      ing: "k",
      uai: "k",
      iang: "l",
      uang: "l",
      ou: "z",
      ua: "x",
      ia: "x",
      ao: "c",
      ui: "v",
      v: "v",
      in: "b",
      ai: "n",
      iao: "m"
    },
    other: {
      e: 'ee',
      er: 'er',
      ei: 'ei',
      eng: 'eg',
      en: 'en',
      ou: 'ou',
      o: 'oo',
      ai: 'ai',
      ao: 'ao',
      a: 'aa',
      ang: 'ad',
      an: 'an'
    }
  }
}
