/** last changed: 2022.3.6 */

Shuang.resource.scheme.xingkong = {
  id: 'xingkong',
  name: '星空双拼',
  tips: [
    '常用输入法不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'c',
      sh: 's',
      zh: 'z'
    },
    yun: {
      a: 'a',
      ai: 'h',
      an: 'j',
      ang: 'p',
      ao: 'k',
      e: 'e',
      ei: 'w',
      en: 'n',
      eng: 'm',
      i: 'i',
      ia: 's',
      ian: 'f',
      iang: 'c',
      iao: 'd',
      ie: 'x',
      iong: 'l',
      in: 'b',
      ing: 'g',
      iu: 'q',
      o: 'o',
      ong: 'l',
      ou: 'r',
      u: 'u',
      ua: 's',
      uai: 'g',
      uan: 't',
      uang: 'c',
      ue: ['h','z' ],
      ui: 'v',
      un: 'y',
      uo: 'o',
      v: 'v',
      ve: ['h','z']
    },
    other: {
      a: 'va',
      ai: 'vh',
      an: 'vj',
      ang: 'vp',
      ao: 'vk',
      e: 've',
      ei: 'vw',
      en: 'vn',
      eng: 'vm',
      er: 'vu',
      o: 'vo',
      ou: 'vr'
    }
  }
}