/** last changed: 2020.6.25 */

Shuang.resource.scheme.yunbiaokuaipin = {
  id: 'yunbiaokuaipin',
  name: '韵标块拼',
  tips: [
    '常用输入法不内置'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      zh: 'a',
      ch: 'u',
      sh: 'i'
    },
    yun: {
      a: 'a',
      ai: 'p',
      an: 'z',
      ang: 'm',
      ao: 'c',
      e: 'e',
      ei: 'k',
      en: 'n',
      eng: 't',
      i: 'i',
      ia: 'j',
      ian: 'q',
      iang: 'r',
      iao: 'f',
      ie: 'y',
      iong: 'h',
      in: 'b',
      ing: 'g',
      iu: 'x',
      o: 'o',
      ong: 'h',
      ou: 'l',
      u: 'u',
      ua: 'w',
      uai: 'y',
      uan: 'd',
      uang: 'g',
      ue: 'w',
      ui: 'v',
      un: 's',
      uo: 'o',
      v: 'u',
      ve: 'w'
    },
    other: {
      a: 'ea',
      ai: 'ep',
      an: 'ez',
      ang: 'em',
      ao: 'ec',
      e: 'ee',
      ei: 'eb',
      en: 'en',
      eng: 'eh',
      er: 'er',
      o: 'eo',
      ou: 'el'
    }
  }
}