/** last changed: 2020.5.3 */

Shuang.resource.scheme.zhinengabc = {
  id: 'zhinengabc',
  name: '智能ABC',
  tips: [
    'macOS 默认方案'
  ],
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'e',
      sh: 'v',
      zh: 'a'
    },
    yun: {
      a: 'a',
      ai: 'l',
      an: 'j',
      ang: 'h',
      ao: 'k',
      e: 'e',
      ei: 'q',
      en: 'f',
      eng: 'g',
      i: 'i',
      ia: 'd',
      ian: 'w',
      iang: 't',
      iao: 'z',
      ie: 'x',
      iong: 's',
      in: 'c',
      ing: 'y',
      iu: 'r',
      o: 'o',
      ong: 's',
      ou: 'b',
      u: 'u',
      ua: 'd',
      uai: 'c',
      uan: 'p',
      uang: 't',
      ue: ['m', 'v'],
      ui: 'm',
      un: 'n',
      uo: 'o',
      v: 'v',
      ve: ['m', 'v']
    },
    other: {
      a: 'oa',
      ai: 'ol',
      an: 'oj',
      ang: 'oh',
      ao: 'ok',
      e: 'oe',
      ei: 'oq',
      en: 'of',
      eng: 'og',
      er: 'or',
      o: 'oo',
      ou: 'ob'
    }
  }
}